### PR TITLE
Add some documentation notes, fix for create script

### PR DESCRIPTION
**Pull request by dannyman**
Please consider these changes. My change to the create script is ugly, though, but it works here.

### CODE REVIEW

**Comment by paurkedal** [comment]
Could you skip the changes to the `create` function in this PR?  I'll make a PR for mapping shortly based on the debootstreap OS.

**Comment by dannyman** [comment]
Petter, how does this look? I have a sample user-data file I can send over.

**Comment by dannyman** [comment]
Ah, shoot how about I'll submit a new PR after the fix comes in for `create`. :)

**Comment by paurkedal** [comment]
If you don't mind, I'll cherry-pick 95133241083f71810a31eb5e8bd708d5728d48af, a61a20789d446c1042f9746d49cbe0a0a0e9ba85, c118ef738c0f8f3440947dfd062a65c9c6ada82c, 878087339249a52446eeba21320641d7508b2821, 2321f87203caf81b46c7c27f5df1e0d56b9b54be, fc1aca4563bdceccdbf06c4f02953620a2469216.

**Pull request closed without merging**
